controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /
    controller: App\Controller\LuckyController::index

app_logout:
    path: /logout
    methods: POST

app_login:
    path: /login
    controller: App\Controller\LoginController::index
api_login:
    path: /api/login
    controller: App\Controller\ApiLoginController::index
    methods: POST

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
api_register:
    path: /api/register
    controller: App\Controller\ApiRegisterController::index
    methods: POST

api_users_show:
    path: /api/users/show
    controller: App\Controller\ApiUsersController::show
    methods: POST
api_user_approve:
    path: /api/user/approve
    controller: App\Controller\ApiUsersController::approve
    methods: POST
api_user_unapprove:
    path: /api/user/unapprove
    controller: App\Controller\ApiUsersController::unapprove
    methods: POST
api_user_edit:
    path: /api/user/edit
    controller: App\Controller\ApiUsersController::edit
    methods: POST
api_user_delete:
    path: /api/user/delete
    controller: App\Controller\ApiUsersController::delete
    methods: POST





